import fs from 'node:fs/promises'

const owner = 'Drecullith'
const repo = 'omacom/omarchy'
const outputPath = new URL('../src/data/omarchy.generated.ts', import.meta.url)

const token = process.env.GITHUB_TOKEN
if (!token) throw new Error('GITHUB_TOKEN is required for the build-time sync')

const query = new URLSearchParams({
  q: `repo:${repo} type:pr author:${owner}`,
  sort: 'created',
  order: 'desc',
  per_page: '100',
})

const response = await fetch(`https://api.github.com/search/issues?${query}`, {
  headers: {
    Accept: 'application/vnd.github+json',
    Authorization: `Bearer ${token}`,
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'DrecSec-portfolio-sync',
  },
})

if (!response.ok) {
  throw new Error(`GitHub API returned ${response.status} ${response.statusText}`)
}

const payload = await response.json()
const items = Array.isArray(payload.items) ? payload.items : []

function linkedIssue(body = '') {
  const match = body.match(/(?:fix(?:e[sd]?|ing)?|close[sd]?|resolve[sd]?)\s+#(\d+)/i)
  return match ? `#${match[1]}` : null
}

function regressionTest(body = '') {
  const matches = [...body.matchAll(/`([^`\n]*test[^`\n]*\.(?:sh|ts|tsx|js|jsx|py))`/gi)]
  return matches[0]?.[1] ?? null
}

const prs = items.map((item) => ({
  number: item.number,
  title: item.title,
  state: item.pull_request?.merged_at ? 'merged' : item.state === 'closed' ? 'closed' : 'open',
  createdAt: item.created_at,
  updatedAt: item.updated_at,
  href: item.html_url,
  issue: linkedIssue(item.body ?? ''),
  test: regressionTest(item.body ?? ''),
}))

const generated = `// Generated by scripts/sync-omarchy.mjs from PUBLIC GitHub PR metadata.\n// Do not place secrets or private-account data in this file.\n\nexport type OmarchyPullRequest = {\n  number: number\n  title: string\n  state: 'open' | 'merged' | 'closed'\n  createdAt: string\n  updatedAt: string\n  href: string\n  issue: string | null\n  test: string | null\n}\n\nexport const omarchyPullRequests: OmarchyPullRequest[] = ${JSON.stringify(prs, null, 2)}\n`

await fs.writeFile(outputPath, generated)
console.log(`Synced ${prs.length} public Omarchy pull request(s) authored by ${owner}.`)
