-- DrecSec v0.2 community foundation
-- Profiles, authenticated posts, channels, real-time messages, and RLS.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (username ~ '^[A-Za-z0-9_]{3,24}$'),
  display_name text check (char_length(display_name) <= 60),
  bio text check (char_length(bio) <= 280),
  skill_level text not null default 'learning' check (skill_level in ('learning', 'practitioner', 'experienced')),
  focus text[] not null default '{}',
  github_url text,
  avatar_url text,
  role text not null default 'member' check (role in ('member', 'moderator', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_username_lower_unique on public.profiles (lower(username));

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null constraint posts_author_id_fkey references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.channels (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]{2,32}$'),
  name text not null check (char_length(name) between 2 and 40),
  description text check (char_length(description) <= 160),
  sort_order integer not null default 0,
  is_archived boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  channel_id bigint not null references public.channels(id) on delete cascade,
  author_id uuid not null constraint messages_author_id_fkey references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists posts_created_at_idx on public.posts (created_at desc);
create index if not exists messages_channel_created_at_idx on public.messages (channel_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.channels enable row level security;
alter table public.messages enable row level security;

create policy "profiles are publicly readable" on public.profiles for select using (true);
create policy "posts are publicly readable" on public.posts for select using (true);
create policy "channels are publicly readable" on public.channels for select using (true);
create policy "messages are publicly readable" on public.messages for select using (true);

create policy "members update own profile" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "members create own posts" on public.posts
  for insert to authenticated with check (auth.uid() = author_id);
create policy "members delete own posts" on public.posts
  for delete to authenticated using (auth.uid() = author_id);

create policy "members create own messages" on public.messages
  for insert to authenticated with check (auth.uid() = author_id);
create policy "members delete own messages" on public.messages
  for delete to authenticated using (auth.uid() = author_id);

revoke insert on public.profiles from anon, authenticated;
revoke update on public.profiles from authenticated;
grant update (username, display_name, bio, skill_level, focus, github_url, avatar_url, updated_at) on public.profiles to authenticated;

grant select on public.profiles, public.posts, public.channels, public.messages to anon, authenticated;
grant insert, delete on public.posts, public.messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  requested_username text;
begin
  requested_username := coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), 'user_' || left(new.id::text, 8));

  insert into public.profiles (id, username, display_name)
  values (new.id, requested_username, requested_username);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

insert into public.channels (slug, name, description, sort_order)
values
  ('general', 'general', 'General DrecSec discussion.', 10),
  ('introductions', 'introductions', 'Say hello and share what you are learning.', 20),
  ('ctf-help', 'ctf-help', 'CTF methodology and help within authorized environments.', 30),
  ('linux', 'linux', 'Linux, Omarchy, tooling and troubleshooting.', 40),
  ('open-source', 'open-source', 'Open-source projects, reviews and contributions.', 50),
  ('homelab', 'homelab', 'Home labs, networking and defensive practice.', 60)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;
