// Generated by scripts/sync-omarchy.mjs from allowlisted PUBLIC GitHub metadata.
// Current snapshots only; historical release/activity data lives in omarchy-updates.generated.ts.

export type OmarchyPullRequest = {
  number: number
  title: string
  state: 'open' | 'merged' | 'closed'
  createdAt: string
  href: string
  issue: string | null
  test: string | null
}

export type OmarchyTool = {
  id: string
  name: string
  version: string | null
  stage: 'released' | 'build-candidate' | 'public'
  href: string
}

export const omarchyPullRequests: OmarchyPullRequest[] = [
  {
    "number": 11089,
    "title": "Add out-of-band plugin rescue",
    "state": "open",
    "createdAt": "2026-09-10T06:03:01Z",
    "href": "https://github.com/omacom/omarchy/pull/11089",
    "issue": null,
    "test": "test/shell.d/plugin-rescue-test.sh"
  },
  {
    "number": 10905,
    "title": "Validate GNOME icon themes before applying",
    "state": "open",
    "createdAt": "2026-09-08T23:49:05Z",
    "href": "https://github.com/omacom/omarchy/pull/10905",
    "issue": "#7203",
    "test": "test/shell.d/gnome-icon-theme-test.sh"
  },
  {
    "number": 10899,
    "title": "Bound running browser policy refreshes",
    "state": "open",
    "createdAt": "2026-09-08T23:18:02Z",
    "href": "https://github.com/omacom/omarchy/pull/10899",
    "issue": "#10636",
    "test": "test/shell.d/theme-browser-refresh-test.sh"
  },
  {
    "number": 10890,
    "title": "Classify T2 built-in trackpads as internal",
    "state": "open",
    "createdAt": "2026-09-08T22:27:50Z",
    "href": "https://github.com/omacom/omarchy/pull/10890",
    "issue": "#10815",
    "test": "test/shell.d/t2-trackpad-test.sh"
  },
  {
    "number": 10886,
    "title": "Repair T1 Mac PCIe hotplug defaults",
    "state": "open",
    "createdAt": "2026-09-08T22:07:25Z",
    "href": "https://github.com/omacom/omarchy/pull/10886",
    "issue": "#10638",
    "test": "test/shell.d/t1-pcie-hotplug-test.sh"
  },
  {
    "number": 10878,
    "title": "Converge ISO Node pins on normal updates",
    "state": "open",
    "createdAt": "2026-09-08T21:09:08Z",
    "href": "https://github.com/omacom/omarchy/pull/10878",
    "issue": "#10820",
    "test": "test/shell.d/update-mise-test.sh"
  },
  {
    "number": 10877,
    "title": "Target the actual NVMe controller in Apple suspend fix",
    "state": "open",
    "createdAt": "2026-09-08T21:00:30Z",
    "href": "https://github.com/omacom/omarchy/pull/10877",
    "issue": "#10826",
    "test": "test/shell.d/apple-nvme-suspend-test.sh"
  },
  {
    "number": 10872,
    "title": "Limit terminal cwd inheritance to terminal windows",
    "state": "open",
    "createdAt": "2026-09-08T20:45:31Z",
    "href": "https://github.com/omacom/omarchy/pull/10872",
    "issue": "#10840",
    "test": "test/shell.d/terminal-cwd-test.sh"
  },
  {
    "number": 10869,
    "title": "Prevent lock-screen wake loop during idle transition",
    "state": "open",
    "createdAt": "2026-09-08T20:36:12Z",
    "href": "https://github.com/omacom/omarchy/pull/10869",
    "issue": "#10861",
    "test": "test/shell.d/idle-test.sh"
  },
  {
    "number": 10866,
    "title": "Clarify theme-scoped and global settings",
    "state": "open",
    "createdAt": "2026-09-08T20:21:10Z",
    "href": "https://github.com/omacom/omarchy/pull/10866",
    "issue": "#10853",
    "test": null
  },
  {
    "number": 10742,
    "title": "Warn about orphaned legacy Hyprland config",
    "state": "open",
    "createdAt": "2026-09-07T23:42:45Z",
    "href": "https://github.com/omacom/omarchy/pull/10742",
    "issue": "#6933",
    "test": "test/shell.d/upgrade-to-quattro-legacy-hypr-config-test.sh"
  },
  {
    "number": 10623,
    "title": "Fix explicit bar toggle direction",
    "state": "open",
    "createdAt": "2026-09-07T09:58:38Z",
    "href": "https://github.com/omacom/omarchy/pull/10623",
    "issue": "#10621",
    "test": "test/shell.d/toggle-test.sh"
  },
  {
    "number": 10535,
    "title": "Use Ctrl+V for clipboard image paste",
    "state": "open",
    "createdAt": "2026-09-06T19:53:56Z",
    "href": "https://github.com/omacom/omarchy/pull/10535",
    "issue": "#10526",
    "test": "test/shell.d/clipboard-file-paste-test.sh"
  },
  {
    "number": 10513,
    "title": "Drop browser codec preloads from yt-dlp host",
    "state": "open",
    "createdAt": "2026-09-06T17:07:23Z",
    "href": "https://github.com/omacom/omarchy/pull/10513",
    "issue": "#10469",
    "test": "test/shell.d/chromium-ytdlp-preload-test.sh"
  },
  {
    "number": 10501,
    "title": "Keep Bluetooth device actions on the panel adapter",
    "state": "open",
    "createdAt": "2026-09-06T16:34:07Z",
    "href": "https://github.com/omacom/omarchy/pull/10501",
    "issue": "#10479",
    "test": "test/shell.d/bluetooth-multi-adapter-test.sh"
  },
  {
    "number": 10497,
    "title": "Restore GVfs mounts after system resume",
    "state": "open",
    "createdAt": "2026-09-06T15:56:31Z",
    "href": "https://github.com/omacom/omarchy/pull/10497",
    "issue": "#10450",
    "test": "test/shell.d/unmount-fuse-test.sh"
  },
  {
    "number": 10490,
    "title": "Scope 1Password floating geometry to main window",
    "state": "open",
    "createdAt": "2026-09-06T15:23:56Z",
    "href": "https://github.com/omacom/omarchy/pull/10490",
    "issue": null,
    "test": "test/shell.d/hyprland-1password-rules-test.sh"
  }
]

export const omarchyTools: OmarchyTool[] = [
  {
    "id": "contrib:plugin-rescue",
    "name": "Omarchy Plugin Rescue",
    "version": "v1.0.1",
    "stage": "released",
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/plugin-rescue"
  },
  {
    "id": "contrib:rollback-check",
    "name": "Omarchy Rollback Check + Guided Recovery",
    "version": "v1.0.0",
    "stage": "released",
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/rollback-check"
  },
  {
    "id": "contrib:migration-check",
    "name": "Omarchy Migration Check",
    "version": "v1.0.0",
    "stage": "released",
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/migration-check"
  },
  {
    "id": "contrib:context-snapshot",
    "name": "Omarchy Context Snapshot",
    "version": "v1.0.0",
    "stage": "released",
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/context-snapshot"
  },
  {
    "id": "repo:omarchy-scope",
    "name": "SCOPE",
    "version": "v0.1.0",
    "stage": "build-candidate",
    "href": "https://github.com/Drecullith/omarchy-scope"
  }
]
