// Generated by scripts/sync-omarchy.mjs from allowlisted PUBLIC GitHub milestones.
// Release history comes only from Drecullith/Omarchy-Contributions tools/*/CHANGELOG.md.
// No commit messages, profiles, emails, secrets, environment values, or arbitrary repository files are stored here.

export type OmarchyReleaseUpdate = {
  id: string
  kind: 'release'
  date: string
  name: string
  version: string
  bullets: string[]
  href: string
}

export type OmarchyPrUpdate = {
  id: string
  kind: 'pr'
  date: string
  event: 'opened' | 'merged' | 'closed'
  prNumber: number
  title: string
  href: string
}

export type OmarchyUpdate = OmarchyReleaseUpdate | OmarchyPrUpdate

export const omarchyUpdates: OmarchyUpdate[] = [
  {
    "id": "release:contrib:context-snapshot:omarchy-context-snapshot:v1.0.0:2026-09-10",
    "kind": "release",
    "date": "2026-09-10",
    "name": "Omarchy Context Snapshot",
    "version": "v1.0.0",
    "bullets": [
      "Add omcontext quick, baseline, incident, diff, and show.",
      "Add stable snapshot/delta schema version 1.",
      "Compare package versions, migration markers, selected config fingerprints, failed services, Omarchy metadata, and disk usage against a known-good baseline.",
      "Add bounded sanitized current-boot journal evidence.",
      "Add private atomic state storage, root refusal, symlink guards, and post-collection privacy scan.",
      "Add isolated regression coverage and installer smoke-test support."
    ],
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/context-snapshot"
  },
  {
    "id": "release:contrib:plugin-rescue:omarchy-plugin-rescue:v1.0.1:2026-09-10",
    "kind": "release",
    "date": "2026-09-10",
    "name": "Omarchy Plugin Rescue",
    "version": "v1.0.1",
    "bullets": [
      "Serialize rescue/restore state mutation with a non-blocking flock.",
      "Abort rescue if shell.json changes after the snapshot but before the safe configuration is installed.",
      "Add regression coverage for concurrent-operation locking.",
      "Document the new safety behavior and flock dependency."
    ],
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/plugin-rescue"
  },
  {
    "id": "release:contrib:rollback-check:guided-recovery:v1.0.0:2026-09-10",
    "kind": "release",
    "date": "2026-09-10",
    "name": "Guided Recovery",
    "version": "v1.0.0",
    "bullets": [
      "Added omrollback-plan, a read-only guided recovery companion to omrollback-check.",
      "Added optional correlation with Omarchy Context Snapshot schema-v1 delta JSON.",
      "Added stable plan schema v1 for deterministic tools and future local-assistant consumers.",
      "Added distinct recovery sequences for CONFIRMED, POTENTIAL, INCOMPLETE, and clean rollback evidence.",
      "Explicitly blocks automatic snapshot restore, migration replay/marker deletion, package changes, config overwrite, and service mutation.",
      "Added isolated tests for classification, Context Snapshot parsing, JSON output, mutation guards, root refusal, and unsupported schemas."
    ],
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/rollback-check"
  },
  {
    "id": "release:contrib:migration-check:omarchy-migration-check:v1.0.0:2026-09-07",
    "kind": "release",
    "date": "2026-09-07",
    "name": "Omarchy Migration Check",
    "version": "v1.0.0",
    "bullets": [
      "Initial release.",
      "Add a read-only Quattro audit for known legacy Hyprland core .conf files.",
      "Classify configuration-bearing remnants as POSSIBLY_IGNORED without claiming automatic proof of lost user settings.",
      "Keep blank/comment-only remnants informational as LEGACY.",
      "Recognize the legacy-provider shape when no hyprland.lua entry point exists.",
      "Exclude current standalone configs such as hyprsunset.conf and xdph.conf.",
      "Provide manual Lua review targets without converting or deleting anything.",
      "Add isolated regression tests, installer coverage, research notes, and CI integration."
    ],
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/migration-check"
  },
  {
    "id": "release:contrib:plugin-rescue:omarchy-plugin-rescue:v1.0.0:2026-09-06",
    "kind": "release",
    "date": "2026-09-06",
    "name": "Omarchy Plugin Rescue",
    "version": "v1.0.0",
    "bullets": [
      "Initial release.",
      "TTY-safe third-party shell-plugin rescue without requiring Quickshell IPC.",
      "Exact shell.json snapshot and restore.",
      "First-party clone restoration when trusted omarchy.clonedFrom metadata is available.",
      "Stale third-party config-reference cleanup even when plugin files are absent or malformed.",
      "Restore conflict detection with explicit --force escape hatch.",
      "Best-effort Omarchy shell restart with readiness retry.",
      "Isolated regression test suite."
    ],
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/plugin-rescue"
  },
  {
    "id": "release:contrib:rollback-check:rollback-check:v1.0.0:2026-09-06",
    "kind": "release",
    "date": "2026-09-06",
    "name": "Rollback Check",
    "version": "v1.0.0",
    "bullets": [
      "Added read-only root/home rollback-drift diagnostics for Omarchy 4 / Quattro.",
      "Added exact-revision auditing for direct machine-completion invariants.",
      "Added conservative timeline drift detection for split Btrfs root/home layouts.",
      "Added root refusal, dependency checks, explicit result classes, and stable exit codes.",
      "Added isolated regression tests covering false positives, changed upstream migration revisions, conditional/temporary machine markers, non-Btrfs layouts, and non-execution of migration scripts."
    ],
    "href": "https://github.com/Drecullith/Omarchy-Contributions/tree/main/tools/rollback-check"
  }
]
